### ISSUE TITLE
No Selection.json Type Option

### ISSUE THREAD

**Issue by brentbarkley** [kylephillips/acf-icomoon-select#2]
When I try using the plugin, I get several errors:

```Undefined index: selection_json_type in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 176
Warning: file_get_contents(): Filename cannot be empty in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 232
Notice: Trying to get property of non-object in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 234
Notice: Trying to get property of non-object in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 234
Notice: Trying to get property of non-object in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 234
Notice: Trying to get property of non-object in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 236
Warning: Invalid argument supplied for foreach() in ""/acf-icomoon-select/fields/acf-icomoon_select-v5.php on line 236
```
Deactivated all plugins (but ACF) to make sure it wasn't a plugin error. 

ACF v5.6.7
WP 4.9.2

Comparing to your grab, I see no Selection.json Type option in my install (attached). (Disregard Hide Label--add-on plugin that was cycled off while testing this.)

![acf-icomoon-select-error](https://user-images.githubusercontent.com/20509017/35263662-919065f2-ffce-11e7-8dfb-ecd25f0f0a7a.jpg)

**Comment by danielemucilli** [comment]
Hey, @brentbarkley you need to add to your function.php this filter:
`function cc_mime_types($mimes) {
  $mimes['json'] = 'application/json';
  return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');`
